---
- name: Update apt to the latest version
  command: apt-get install -y aptitude

- name: Update and upgrade packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
    
- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - jq
      - python-pip
      

- name: Update and upgrade after installing packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day      