---
- name: Install docker.io
  package:
    name: docker.io
    state: latest

- name: Install docker-py
  pip:
    name: docker-py

- name: Ensure docker-compose is installed and available
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.23.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}          
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,a+x'