---
- name: Clone ldm.base and checkout the designated branch ldm.base-2.8.2
  git:
    repo: https://github.com/TIBHannover/ldm.base.git
    version: ldm.base-2.8.2
    dest: /home/vagrant/ldm.base

- name: Build the .env file and set the credentials 
  command: cp .env.template .env
  args:
    chdir: /home/vagrant/ldm.base/contrib/docker

# use this with care, the flag removes the volumes from the host.
- name: Drop all the images and volumes
  command: docker system prune -f --volumes
  args:
    chdir: /home/vagrant/ldm.base/contrib/docker
 
- name: Remove existing containers
  command: docker-compose rm -f
  args:
    chdir: /home/vagrant/ldm.base/contrib/docker

- name: Build docker images
  command: docker-compose build --force-rm
  args:
    chdir: /home/vagrant/ldm.base/contrib/docker
    
- name: Change site's URL in docker-compose.yml
  lineinfile:
    path: '/home/vagrant/ldm.base/contrib/docker/docker-compose.yml'
    line: '      - CKAN_SITE_URL=http://192.168.98.106:5000
    regexp: '     - CKAN_SITE_URL='

# Enable plugins in the config file. try to have an LDM entry-point and run it after/ instead of the ckan entrypoint

# This may init docker pull from corresponsing repos
- name: Start the depenencies
  command: docker-compose up -d datapusher redis solr db
  args:
    chdir: /home/vagrant/ldm.base/contrib/docker

- name: Start LDM
  command: docker-compose up -d ckan
  args:
    chdir: /home/vagrant/ldm.base/contrib/docker
    
