Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64" # debian:jessie
  config.vm.network :private_network, ip: "192.168.98.106"

  config.vm.provision "ansible_local" do |ansible|
    ansible.install = true
    ansible.version = "latest"
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "ansible/ldm.base.yml"
  end
end
